### ISSUE TITLE
Create data frame for response

### ISSUE THREAD

**Issue by orhanemree** [AlexanderEllis/websocket-from-scratch#1]
Hi,

For a long time, i have been looking a websocket server structure without library and i found this repo from the blog post, finally! Thanks you so much for explaining the process from scratch first of all. It is really helpful.

But there is something i couldn't do. We can get sent data with parsing the data frame. But what would we have done if we wanted to create a response as a data frame from scratch? I mean how can we send message to clients? (as you mentioned at the incomplete list)

I would be glad if you help me, thanks!

**Comment by AlexanderEllis** [comment]
Hey @orhanemree ! Thanks for the kind words, and glad you enjoyed!

The message sending would be pretty similar to what [we're doing](https://github.com/AlexanderEllis/websocket-from-scratch/blob/main/server.py#L80) in `handle_websocket_message`:
```
    data_in_bytes = client_socket.recv(BUFFER_SIZE)
    websocket_frame = toy_websocket_frame.WebsocketFrame()
    websocket_frame.populateFromWebsocketFrameMessage(data_in_bytes)
```

The only difference is you'd need to do everything in reverse:
- Create a websocket_frame object with the message you'd like to send
- Convert it to bytes (I could see that being a class method, like `serializeToBytes` or something like that)
- Write it to the client socket


If you're into it, I'd say you should start with the server sending a super simple text websocket frame message. You could start with a WS connection in your browser, kind of like I did in the blog post, but also add an [event listener](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#events) for messages — hopefully eventually you'll see your server send something back. I'd recommend that you start with the [spec](https://datatracker.ietf.org/doc/html/rfc6455#section-5.2) and try to build one out!

**Comment by orhanemree** [comment]
Hey, thank you for your answer.

I'll definitely check out the references and try to build my own methods.

I wanted to implement websockets support to my tiny http library and this helps a lot, a nice repo will be mentioned as reference.
